### ISSUE TITLE
Hydrawise Home Assistant integration error: last_contact is "Unknown"

### ISSUE THREAD

**Issue by jeffwdoak** [dknowles2/pydrawise#218]
Hi there! I recently got a Hydrawise controller and I'm running into an issue trying to connect it to Home Assistant. I've tracked the issue down to this repo which is why I'm posting the issue here rather than the HA repo or forums. Please let me know if there's a better place to post this.

## The issue:

When trying to add the Hydrawise integration I'm running into an `Unknown Error`. From the home assistant logs the issue seems to be trying to parse  `"last_contact": "Unknown"` as a datetime in the legacy pydrawise API when calling `get_user`.

I'm able to connect and control my Hydrawise controller through the Android app so I don't think there's anything wrong with my physical setup.

The Hydrawise API docs ([v1.6 here](https://www.hunterindustries.com/support/hydrawise-api-information)) suggest that the `last_contact` field is deprecated, which makes me think I will always see "Unknown" as the value for `last_contact`.
```
last_contact string Depreciated
```

Is this a known issue with a workaround? Or does `_controller_from_json` need to be updated to handle "Unknown"?

Thanks in advance for your help!

### Most relevant part
```
File "/usr/local/lib/python3.11/site-packages/pydrawise/legacy.py", line 226, in _controller_from_json
    last_contact_time=datetime.fromtimestamp(controller_json["last_contact"]),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object cannot be interpreted as an integer
```

### Full logs
```
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: October 21, 2024 at 1:23:54 PM (4 occurrences)
Last logged: 6:13:34 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 416, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hydrawise/config_flow.py", line 82, in async_step_user
    return await self._create_entry(api_key, on_failure=self._show_form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hydrawise/config_flow.py", line 33, in _create_entry
    user = await api.get_user(fetch_zones=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydrawise/legacy.py", line 59, in get_user
    controllers=[_controller_from_json(c) for c in resp_json["controllers"]],
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydrawise/legacy.py", line 59, in <listcomp>
    controllers=[_controller_from_json(c) for c in resp_json["controllers"]],
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydrawise/legacy.py", line 226, in _controller_from_json
    last_contact_time=datetime.fromtimestamp(controller_json["last_contact"]),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object cannot be interpreted as an integer

```

### request
```
curl -X GET 'https://api.hydrawise.com/api/v1/customerdetails.php?api_key=AAAA-BBBB-CCCC-DDDD'
```
### response
```
{
  "controller_id": YYYYYYY,
  "customer_id": ZZZZZZZ,
  "current_controller": "Garage Sprinkler Controller",
  "controllers": [
    {
      "name": "Garage Sprinkler Controller",
      "last_contact": "Unknown",
      "serial_number": "XXXXXXXXXX",
      "controller_id": YYYYYYY,
      "status": "Unknown"
    }
  ]
}
```

**Comment by dknowles2** [comment]
It looks like you're using an old version of Home Assistant. The integration was updated to use the newer Hydrawise API in 2024.5, and it does not have this problem.

**Comment by jeffwdoak** [comment]
Ah, thank you very much!
